apiVersion: v1
kind: Secret
metadata:
  name: ethereum
  namespace: services
type: Opaque
data:
  infura-api-key: {{ .Files.Get "secrets/infura-api-key" | trim | b64enc | default "dummy-secret-value"}}
