{{ $files := .Files }}
{{ $grafana_path := "secrets/grafana"}}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: observability
type: Opaque
data: 
{{- range tuple "admin-user" "admin-password" }}
  {{ . -}}: {{ printf "%s/%s" $grafana_path . | $files.Get | trimSuffix "\n" | b64enc -}}
{{- end -}}
